spring.application.name=OrderMS

# Server Configuration
server.port=9094

# Datasource Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/orderDB

spring.data.mongodb.repositories.enabled=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
